sudo: required
services:
  - docker

before_install:
  - docker build -t milhamhidayat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run milhamhidayat/react-test npm test -- --coverage

after_success:
  - docker build -t milhamhidayat/multi-client ./client
  - docker build -t milhamhidayat/multi-nginx ./nginx
  - docker build -t milhamhidayat/multi-server ./server
  - docker build -t milhamhidayat/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - sudo docker push milhamhidayat/multi-client
  - sudo docker push milhamhidayat/multi-nginx
  - sudo docker push milhamhidayat/multi-server
  - sudo docker push milhamhidayat/multi-worker